### ISSUE TITLE
Home gets me to tutorial

### ISSUE THREAD

**Issue by Giftpflanze** [wingertge/project-memory-issues#7] opened 2019-05-10 02:35 UTC
I clicked to get to the home and landed in the tutorial and was asked to double check the automatically assigned username. Before that I added a bunch of languages to my profile (but I doubt it is related).

**Comment by wingertge** [comment] 2019-05-10 10:04
Did you complete that step before? Home should redirect to the tutorial until it's completed.

**Comment by Giftpflanze** [comment] 2019-05-10 10:23
Yes, I have completed that step already.

**Comment by wingertge** [comment] 2019-05-10 10:25
That's odd, seems your profile wasn't updated correctly and your intro step was reset to the username step. Difficult to trace though since it seems like an outliar, closing until or unless it happens again.

**Comment by Giftpflanze** [comment] 2019-05-12 16:12
It just happened again.

**Comment by wingertge** [comment] 2019-05-12 16:16
I have a hunch it might have to do with an outdated login, causing the introStep to be undefined, but I'm not sure. I'm rolling out a fix that would prevent that issue so tell me if it happens again from now on.

**Comment by wingertge** [comment] 2019-05-13 11:04
Finally managed to reproduce, fixed in next commit

**Closed by wingertge** 2019-05-13 11:04 UTC
Labels: bug

**Comment by wingertge** [comment] 2019-05-13 12:02
Fixed in 7512a40
