### ISSUE TITLE
Login redirect loop

### ISSUE THREAD

**Issue by Giftpflanze** [wingertge/project-memory-issues#17] opened 2019-05-10 20:58 UTC
When I’m logged in and visit the landing page and click the button to join the community, a blank page appears. I remember there being an error message about too many redirects.

**Comment by wingertge** [comment] 2019-05-11 12:16
That's strange, I can't reproduce it on my setup. Is there any output in your console?

**Comment by wingertge** [comment] 2019-05-11 12:17
Oops, misread that. I'll look into it.

**Comment by wingertge** [comment] 2019-05-11 12:20
This is why copy paste is bad. I accidentally set the unauthenticated route to redirect to the login if the user is logged in because of copy paste. Fixing in the next commit, but need to finish another bug fix first.

**Comment by wingertge** [comment] 2019-05-11 12:51
Fixed in de49ec7

**Closed by wingertge** 2019-05-11 12:51 UTC
Labels: bug
